drop table documents.user_notification;

create table if not exists documents.comment_notification(
	comment_notification_id bigint generated by default as identity(start with 0) primary key,
	user_id bigint not null, -- the owner of the document
	comment_user_id bigint not null, -- the owner of the comment
	comment_id bigint not null,
	section_title varchar(50),
  	date_created timestamp not null
  	);
  	
create table if not exists documents.feedback_request_notification(
	feedback_request_notification_id bigint generated by default as identity(start with 0) primary key,
	user_id bigint not null, -- the owner of the notification 
	resume_user_id bigint not null,
	resume_id bigint not null,
  	date_created timestamp not null
  	);

