drop table documents.user_notification;

--alter table documents.user_notification rename to documents.comment_notification;

create table if not exists documents.comment_notification(
	comment_notification_id bigint generated by default as identity(start with 0) primary key,
	user_id bigint not null, -- the owner of the document
	comment_id bigint not null,
  	date_created timestamp not null
  	);

