create schema if not exists CONNECTIONS;

create table if not exists CONNECTIONS.contacts(
	id bigint generated by default as identity(start with 1) primary key,
  	username varchar_ignorecase(50) not null );
  	

