/**
 * This class is generated by jOOQ
 */
package editor.domain.information_schema;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationSchema extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1635037854;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA</code>
	 */
	public static final InformationSchema INFORMATION_SCHEMA = new InformationSchema();

	/**
	 * No further instances allowed
	 */
	private InformationSchema() {
		super("INFORMATION_SCHEMA");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			editor.domain.information_schema.tables.QueryStatistics.QUERY_STATISTICS,
			editor.domain.information_schema.tables.SessionState.SESSION_STATE,
			editor.domain.information_schema.tables.Locks.LOCKS,
			editor.domain.information_schema.tables.Sessions.SESSIONS,
			editor.domain.information_schema.tables.Triggers.TRIGGERS,
			editor.domain.information_schema.tables.Domains.DOMAINS,
			editor.domain.information_schema.tables.Constants.CONSTANTS,
			editor.domain.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS,
			editor.domain.information_schema.tables.Constraints.CONSTRAINTS,
			editor.domain.information_schema.tables.CrossReferences.CROSS_REFERENCES,
			editor.domain.information_schema.tables.InDoubt.IN_DOUBT,
			editor.domain.information_schema.tables.Views.VIEWS,
			editor.domain.information_schema.tables.Collations.COLLATIONS,
			editor.domain.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES,
			editor.domain.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES,
			editor.domain.information_schema.tables.Schemata.SCHEMATA,
			editor.domain.information_schema.tables.FunctionAliases.FUNCTION_ALIASES,
			editor.domain.information_schema.tables.Rights.RIGHTS,
			editor.domain.information_schema.tables.Roles.ROLES,
			editor.domain.information_schema.tables.Users.USERS,
			editor.domain.information_schema.tables.Sequences.SEQUENCES,
			editor.domain.information_schema.tables.Help.HELP,
			editor.domain.information_schema.tables.Settings.SETTINGS,
			editor.domain.information_schema.tables.Catalogs.CATALOGS,
			editor.domain.information_schema.tables.TypeInfo.TYPE_INFO,
			editor.domain.information_schema.tables.TableTypes.TABLE_TYPES,
			editor.domain.information_schema.tables.Indexes.INDEXES,
			editor.domain.information_schema.tables.Columns.COLUMNS,
			editor.domain.information_schema.tables.Tables.TABLES);
	}
}
