/**
 * This class is generated by jOOQ
 */
package editor.domain.information_schema;

/**
 * Convenience access to all tables in INFORMATION_SCHEMA
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table INFORMATION_SCHEMA.QUERY_STATISTICS
	 */
	public static final editor.domain.information_schema.tables.QueryStatistics QUERY_STATISTICS = editor.domain.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

	/**
	 * The table INFORMATION_SCHEMA.SESSION_STATE
	 */
	public static final editor.domain.information_schema.tables.SessionState SESSION_STATE = editor.domain.information_schema.tables.SessionState.SESSION_STATE;

	/**
	 * The table INFORMATION_SCHEMA.LOCKS
	 */
	public static final editor.domain.information_schema.tables.Locks LOCKS = editor.domain.information_schema.tables.Locks.LOCKS;

	/**
	 * The table INFORMATION_SCHEMA.SESSIONS
	 */
	public static final editor.domain.information_schema.tables.Sessions SESSIONS = editor.domain.information_schema.tables.Sessions.SESSIONS;

	/**
	 * The table INFORMATION_SCHEMA.TRIGGERS
	 */
	public static final editor.domain.information_schema.tables.Triggers TRIGGERS = editor.domain.information_schema.tables.Triggers.TRIGGERS;

	/**
	 * The table INFORMATION_SCHEMA.DOMAINS
	 */
	public static final editor.domain.information_schema.tables.Domains DOMAINS = editor.domain.information_schema.tables.Domains.DOMAINS;

	/**
	 * The table INFORMATION_SCHEMA.CONSTANTS
	 */
	public static final editor.domain.information_schema.tables.Constants CONSTANTS = editor.domain.information_schema.tables.Constants.CONSTANTS;

	/**
	 * The table INFORMATION_SCHEMA.FUNCTION_COLUMNS
	 */
	public static final editor.domain.information_schema.tables.FunctionColumns FUNCTION_COLUMNS = editor.domain.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

	/**
	 * The table INFORMATION_SCHEMA.CONSTRAINTS
	 */
	public static final editor.domain.information_schema.tables.Constraints CONSTRAINTS = editor.domain.information_schema.tables.Constraints.CONSTRAINTS;

	/**
	 * The table INFORMATION_SCHEMA.CROSS_REFERENCES
	 */
	public static final editor.domain.information_schema.tables.CrossReferences CROSS_REFERENCES = editor.domain.information_schema.tables.CrossReferences.CROSS_REFERENCES;

	/**
	 * The table INFORMATION_SCHEMA.IN_DOUBT
	 */
	public static final editor.domain.information_schema.tables.InDoubt IN_DOUBT = editor.domain.information_schema.tables.InDoubt.IN_DOUBT;

	/**
	 * The table INFORMATION_SCHEMA.VIEWS
	 */
	public static final editor.domain.information_schema.tables.Views VIEWS = editor.domain.information_schema.tables.Views.VIEWS;

	/**
	 * The table INFORMATION_SCHEMA.COLLATIONS
	 */
	public static final editor.domain.information_schema.tables.Collations COLLATIONS = editor.domain.information_schema.tables.Collations.COLLATIONS;

	/**
	 * The table INFORMATION_SCHEMA.COLUMN_PRIVILEGES
	 */
	public static final editor.domain.information_schema.tables.ColumnPrivileges COLUMN_PRIVILEGES = editor.domain.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_PRIVILEGES
	 */
	public static final editor.domain.information_schema.tables.TablePrivileges TABLE_PRIVILEGES = editor.domain.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

	/**
	 * The table INFORMATION_SCHEMA.SCHEMATA
	 */
	public static final editor.domain.information_schema.tables.Schemata SCHEMATA = editor.domain.information_schema.tables.Schemata.SCHEMATA;

	/**
	 * The table INFORMATION_SCHEMA.FUNCTION_ALIASES
	 */
	public static final editor.domain.information_schema.tables.FunctionAliases FUNCTION_ALIASES = editor.domain.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

	/**
	 * The table INFORMATION_SCHEMA.RIGHTS
	 */
	public static final editor.domain.information_schema.tables.Rights RIGHTS = editor.domain.information_schema.tables.Rights.RIGHTS;

	/**
	 * The table INFORMATION_SCHEMA.ROLES
	 */
	public static final editor.domain.information_schema.tables.Roles ROLES = editor.domain.information_schema.tables.Roles.ROLES;

	/**
	 * The table INFORMATION_SCHEMA.USERS
	 */
	public static final editor.domain.information_schema.tables.Users USERS = editor.domain.information_schema.tables.Users.USERS;

	/**
	 * The table INFORMATION_SCHEMA.SEQUENCES
	 */
	public static final editor.domain.information_schema.tables.Sequences SEQUENCES = editor.domain.information_schema.tables.Sequences.SEQUENCES;

	/**
	 * The table INFORMATION_SCHEMA.HELP
	 */
	public static final editor.domain.information_schema.tables.Help HELP = editor.domain.information_schema.tables.Help.HELP;

	/**
	 * The table INFORMATION_SCHEMA.SETTINGS
	 */
	public static final editor.domain.information_schema.tables.Settings SETTINGS = editor.domain.information_schema.tables.Settings.SETTINGS;

	/**
	 * The table INFORMATION_SCHEMA.CATALOGS
	 */
	public static final editor.domain.information_schema.tables.Catalogs CATALOGS = editor.domain.information_schema.tables.Catalogs.CATALOGS;

	/**
	 * The table INFORMATION_SCHEMA.TYPE_INFO
	 */
	public static final editor.domain.information_schema.tables.TypeInfo TYPE_INFO = editor.domain.information_schema.tables.TypeInfo.TYPE_INFO;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_TYPES
	 */
	public static final editor.domain.information_schema.tables.TableTypes TABLE_TYPES = editor.domain.information_schema.tables.TableTypes.TABLE_TYPES;

	/**
	 * The table INFORMATION_SCHEMA.INDEXES
	 */
	public static final editor.domain.information_schema.tables.Indexes INDEXES = editor.domain.information_schema.tables.Indexes.INDEXES;

	/**
	 * The table INFORMATION_SCHEMA.COLUMNS
	 */
	public static final editor.domain.information_schema.tables.Columns COLUMNS = editor.domain.information_schema.tables.Columns.COLUMNS;

	/**
	 * The table INFORMATION_SCHEMA.TABLES
	 */
	public static final editor.domain.information_schema.tables.Tables TABLES = editor.domain.information_schema.tables.Tables.TABLES;
}
