/**
 * This class is generated by jOOQ
 */
package editor.domain.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comments extends org.jooq.impl.TableImpl<editor.domain.public_.tables.records.CommentsRecord> {

	private static final long serialVersionUID = 1334981879;

	/**
	 * The reference instance of <code>PUBLIC.COMMENTS</code>
	 */
	public static final editor.domain.public_.tables.Comments COMMENTS = new editor.domain.public_.tables.Comments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.public_.tables.records.CommentsRecord> getRecordType() {
		return editor.domain.public_.tables.records.CommentsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.COMMENTS.ID</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.CommentsRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.COMMENTS.SECTIONID</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.CommentsRecord, java.lang.Long> SECTIONID = createField("SECTIONID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.COMMENTS.USERNAME</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.CommentsRecord, java.lang.String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.COMMENTS.COMMENTID</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.CommentsRecord, java.lang.Long> COMMENTID = createField("COMMENTID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>PUBLIC.COMMENTS.LASTMODIFIED</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.CommentsRecord, java.sql.Timestamp> LASTMODIFIED = createField("LASTMODIFIED", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.COMMENTS</code> table reference
	 */
	public Comments() {
		this("COMMENTS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.COMMENTS</code> table reference
	 */
	public Comments(java.lang.String alias) {
		this(alias, editor.domain.public_.tables.Comments.COMMENTS);
	}

	private Comments(java.lang.String alias, org.jooq.Table<editor.domain.public_.tables.records.CommentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Comments(java.lang.String alias, org.jooq.Table<editor.domain.public_.tables.records.CommentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<editor.domain.public_.tables.records.CommentsRecord, java.lang.Long> getIdentity() {
		return editor.domain.public_.Keys.IDENTITY_COMMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<editor.domain.public_.tables.records.CommentsRecord> getPrimaryKey() {
		return editor.domain.public_.Keys.CONSTRAINT_AB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<editor.domain.public_.tables.records.CommentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<editor.domain.public_.tables.records.CommentsRecord>>asList(editor.domain.public_.Keys.CONSTRAINT_AB);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.public_.tables.Comments as(java.lang.String alias) {
		return new editor.domain.public_.tables.Comments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.public_.tables.Comments rename(java.lang.String name) {
		return new editor.domain.public_.tables.Comments(name, null);
	}
}
