/**
 * This class is generated by jOOQ
 */
package editor.domain.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Documents extends org.jooq.impl.TableImpl<editor.domain.public_.tables.records.DocumentsRecord> {

	private static final long serialVersionUID = -1615815608;

	/**
	 * The reference instance of <code>PUBLIC.DOCUMENTS</code>
	 */
	public static final editor.domain.public_.tables.Documents DOCUMENTS = new editor.domain.public_.tables.Documents();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.public_.tables.records.DocumentsRecord> getRecordType() {
		return editor.domain.public_.tables.records.DocumentsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.DOCUMENTS.ID</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.DocumentsRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.DOCUMENTS.ACCOUNTID</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.DocumentsRecord, java.lang.Long> ACCOUNTID = createField("ACCOUNTID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DOCUMENTS.VISIBILITY</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.DocumentsRecord, java.lang.Boolean> VISIBILITY = createField("VISIBILITY", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DOCUMENTS.DATECREATED</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.DocumentsRecord, java.sql.Timestamp> DATECREATED = createField("DATECREATED", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DOCUMENTS.LASTMODIFIED</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.DocumentsRecord, java.sql.Timestamp> LASTMODIFIED = createField("LASTMODIFIED", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.DOCUMENTS</code> table reference
	 */
	public Documents() {
		this("DOCUMENTS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.DOCUMENTS</code> table reference
	 */
	public Documents(java.lang.String alias) {
		this(alias, editor.domain.public_.tables.Documents.DOCUMENTS);
	}

	private Documents(java.lang.String alias, org.jooq.Table<editor.domain.public_.tables.records.DocumentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Documents(java.lang.String alias, org.jooq.Table<editor.domain.public_.tables.records.DocumentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<editor.domain.public_.tables.records.DocumentsRecord, java.lang.Long> getIdentity() {
		return editor.domain.public_.Keys.IDENTITY_DOCUMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<editor.domain.public_.tables.records.DocumentsRecord> getPrimaryKey() {
		return editor.domain.public_.Keys.CONSTRAINT_D;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<editor.domain.public_.tables.records.DocumentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<editor.domain.public_.tables.records.DocumentsRecord>>asList(editor.domain.public_.Keys.CONSTRAINT_D);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<editor.domain.public_.tables.records.DocumentsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<editor.domain.public_.tables.records.DocumentsRecord, ?>>asList(editor.domain.public_.Keys.FK_DOCUMENTS_ACCOUNTS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.public_.tables.Documents as(java.lang.String alias) {
		return new editor.domain.public_.tables.Documents(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.public_.tables.Documents rename(java.lang.String name) {
		return new editor.domain.public_.tables.Documents(name, null);
	}
}
