/**
 * This class is generated by jOOQ
 */
package editor.domain.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Suggestions extends org.jooq.impl.TableImpl<editor.domain.public_.tables.records.SuggestionsRecord> {

	private static final long serialVersionUID = 46076307;

	/**
	 * The reference instance of <code>PUBLIC.SUGGESTIONS</code>
	 */
	public static final editor.domain.public_.tables.Suggestions SUGGESTIONS = new editor.domain.public_.tables.Suggestions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.public_.tables.records.SuggestionsRecord> getRecordType() {
		return editor.domain.public_.tables.records.SuggestionsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.SUGGESTIONS.ID</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.SuggestionsRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.SUGGESTIONS.SECTIONID</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.SuggestionsRecord, java.lang.Long> SECTIONID = createField("SECTIONID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.SUGGESTIONS.SECTIONVERSION</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.SuggestionsRecord, java.lang.Long> SECTIONVERSION = createField("SECTIONVERSION", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.SUGGESTIONS.USERNAME</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.SuggestionsRecord, java.lang.String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.SUGGESTIONS.LASTMODIFIED</code>.
	 */
	public final org.jooq.TableField<editor.domain.public_.tables.records.SuggestionsRecord, java.sql.Timestamp> LASTMODIFIED = createField("LASTMODIFIED", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.SUGGESTIONS</code> table reference
	 */
	public Suggestions() {
		this("SUGGESTIONS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.SUGGESTIONS</code> table reference
	 */
	public Suggestions(java.lang.String alias) {
		this(alias, editor.domain.public_.tables.Suggestions.SUGGESTIONS);
	}

	private Suggestions(java.lang.String alias, org.jooq.Table<editor.domain.public_.tables.records.SuggestionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Suggestions(java.lang.String alias, org.jooq.Table<editor.domain.public_.tables.records.SuggestionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<editor.domain.public_.tables.records.SuggestionsRecord, java.lang.Long> getIdentity() {
		return editor.domain.public_.Keys.IDENTITY_SUGGESTIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<editor.domain.public_.tables.records.SuggestionsRecord> getPrimaryKey() {
		return editor.domain.public_.Keys.CONSTRAINT_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<editor.domain.public_.tables.records.SuggestionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<editor.domain.public_.tables.records.SuggestionsRecord>>asList(editor.domain.public_.Keys.CONSTRAINT_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<editor.domain.public_.tables.records.SuggestionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<editor.domain.public_.tables.records.SuggestionsRecord, ?>>asList(editor.domain.public_.Keys.FK_SUGGESTIONS_DOCUMENT_SECTIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.public_.tables.Suggestions as(java.lang.String alias) {
		return new editor.domain.public_.tables.Suggestions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.public_.tables.Suggestions rename(java.lang.String name) {
		return new editor.domain.public_.tables.Suggestions(name, null);
	}
}
