/**
 * This class is generated by jOOQ
 */
package editor.domain.public_;

/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<editor.domain.public_.tables.records.AccountsRecord, java.lang.Long> IDENTITY_ACCOUNTS = Identities0.IDENTITY_ACCOUNTS;
	public static final org.jooq.Identity<editor.domain.public_.tables.records.DocumentsRecord, java.lang.Long> IDENTITY_DOCUMENTS = Identities0.IDENTITY_DOCUMENTS;
	public static final org.jooq.Identity<editor.domain.public_.tables.records.DocumentSectionsRecord, java.lang.Long> IDENTITY_DOCUMENT_SECTIONS = Identities0.IDENTITY_DOCUMENT_SECTIONS;
	public static final org.jooq.Identity<editor.domain.public_.tables.records.CommentsRecord, java.lang.Long> IDENTITY_COMMENTS = Identities0.IDENTITY_COMMENTS;
	public static final org.jooq.Identity<editor.domain.public_.tables.records.SuggestionsRecord, java.lang.Long> IDENTITY_SUGGESTIONS = Identities0.IDENTITY_SUGGESTIONS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.AccountsRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
	public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.DocumentsRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
	public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.DocumentSectionsRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
	public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.CommentsRecord> CONSTRAINT_AB = UniqueKeys0.CONSTRAINT_AB;
	public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.SuggestionsRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<editor.domain.public_.tables.records.DocumentsRecord, editor.domain.public_.tables.records.AccountsRecord> FK_DOCUMENTS_ACCOUNTS = ForeignKeys0.FK_DOCUMENTS_ACCOUNTS;
	public static final org.jooq.ForeignKey<editor.domain.public_.tables.records.DocumentSectionsRecord, editor.domain.public_.tables.records.DocumentsRecord> FK_SECTION_DOCUMENTS = ForeignKeys0.FK_SECTION_DOCUMENTS;
	public static final org.jooq.ForeignKey<editor.domain.public_.tables.records.SuggestionsRecord, editor.domain.public_.tables.records.DocumentSectionsRecord> FK_SUGGESTIONS_DOCUMENT_SECTIONS = ForeignKeys0.FK_SUGGESTIONS_DOCUMENT_SECTIONS;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<editor.domain.public_.tables.records.AccountsRecord, java.lang.Long> IDENTITY_ACCOUNTS = createIdentity(editor.domain.public_.tables.Accounts.ACCOUNTS, editor.domain.public_.tables.Accounts.ACCOUNTS.ID);
		public static org.jooq.Identity<editor.domain.public_.tables.records.DocumentsRecord, java.lang.Long> IDENTITY_DOCUMENTS = createIdentity(editor.domain.public_.tables.Documents.DOCUMENTS, editor.domain.public_.tables.Documents.DOCUMENTS.ID);
		public static org.jooq.Identity<editor.domain.public_.tables.records.DocumentSectionsRecord, java.lang.Long> IDENTITY_DOCUMENT_SECTIONS = createIdentity(editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS, editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.ID);
		public static org.jooq.Identity<editor.domain.public_.tables.records.CommentsRecord, java.lang.Long> IDENTITY_COMMENTS = createIdentity(editor.domain.public_.tables.Comments.COMMENTS, editor.domain.public_.tables.Comments.COMMENTS.ID);
		public static org.jooq.Identity<editor.domain.public_.tables.records.SuggestionsRecord, java.lang.Long> IDENTITY_SUGGESTIONS = createIdentity(editor.domain.public_.tables.Suggestions.SUGGESTIONS, editor.domain.public_.tables.Suggestions.SUGGESTIONS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.AccountsRecord> CONSTRAINT_A = createUniqueKey(editor.domain.public_.tables.Accounts.ACCOUNTS, editor.domain.public_.tables.Accounts.ACCOUNTS.ID);
		public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.DocumentsRecord> CONSTRAINT_D = createUniqueKey(editor.domain.public_.tables.Documents.DOCUMENTS, editor.domain.public_.tables.Documents.DOCUMENTS.ID);
		public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.DocumentSectionsRecord> CONSTRAINT_4 = createUniqueKey(editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS, editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.ID, editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.SECTIONVERSION);
		public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.CommentsRecord> CONSTRAINT_AB = createUniqueKey(editor.domain.public_.tables.Comments.COMMENTS, editor.domain.public_.tables.Comments.COMMENTS.ID);
		public static final org.jooq.UniqueKey<editor.domain.public_.tables.records.SuggestionsRecord> CONSTRAINT_2 = createUniqueKey(editor.domain.public_.tables.Suggestions.SUGGESTIONS, editor.domain.public_.tables.Suggestions.SUGGESTIONS.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<editor.domain.public_.tables.records.DocumentsRecord, editor.domain.public_.tables.records.AccountsRecord> FK_DOCUMENTS_ACCOUNTS = createForeignKey(editor.domain.public_.Keys.CONSTRAINT_A, editor.domain.public_.tables.Documents.DOCUMENTS, editor.domain.public_.tables.Documents.DOCUMENTS.ACCOUNTID);
		public static final org.jooq.ForeignKey<editor.domain.public_.tables.records.DocumentSectionsRecord, editor.domain.public_.tables.records.DocumentsRecord> FK_SECTION_DOCUMENTS = createForeignKey(editor.domain.public_.Keys.CONSTRAINT_D, editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS, editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.DOCUMENTID);
		public static final org.jooq.ForeignKey<editor.domain.public_.tables.records.SuggestionsRecord, editor.domain.public_.tables.records.DocumentSectionsRecord> FK_SUGGESTIONS_DOCUMENT_SECTIONS = createForeignKey(editor.domain.public_.Keys.CONSTRAINT_4, editor.domain.public_.tables.Suggestions.SUGGESTIONS, editor.domain.public_.tables.Suggestions.SUGGESTIONS.SECTIONID, editor.domain.public_.tables.Suggestions.SUGGESTIONS.SECTIONVERSION);
	}
}
