/**
 * This class is generated by jOOQ
 */
package editor.domain.public_;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1750689280;

	/**
	 * The reference instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			editor.domain.public_.Sequences.SYSTEM_SEQUENCE_10232954_E341_4FF3_86DB_F199632E839F,
			editor.domain.public_.Sequences.SYSTEM_SEQUENCE_16032E05_D38B_47AE_89AE_0BFB2A6F4F59,
			editor.domain.public_.Sequences.SYSTEM_SEQUENCE_2CAF5AE8_44EF_4B8D_A9BD_D7B709AA6981,
			editor.domain.public_.Sequences.SYSTEM_SEQUENCE_78221786_FE25_408A_ADCE_90FE646C3AFC,
			editor.domain.public_.Sequences.SYSTEM_SEQUENCE_C586067C_49AF_4D7C_8872_E073515E86D6);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			editor.domain.public_.tables.Accounts.ACCOUNTS,
			editor.domain.public_.tables.Documents.DOCUMENTS,
			editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS,
			editor.domain.public_.tables.Comments.COMMENTS,
			editor.domain.public_.tables.Suggestions.SUGGESTIONS);
	}
}
