/**
 * This class is generated by jOOQ
 */
package editor.domain.public_;

/**
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_10232954_E341_4FF3_86DB_F199632E839F</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_10232954_E341_4FF3_86DB_F199632E839F = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_10232954_E341_4FF3_86DB_F199632E839F", editor.domain.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_16032E05_D38B_47AE_89AE_0BFB2A6F4F59</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_16032E05_D38B_47AE_89AE_0BFB2A6F4F59 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_16032E05_D38B_47AE_89AE_0BFB2A6F4F59", editor.domain.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_2CAF5AE8_44EF_4B8D_A9BD_D7B709AA6981</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_2CAF5AE8_44EF_4B8D_A9BD_D7B709AA6981 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_2CAF5AE8_44EF_4B8D_A9BD_D7B709AA6981", editor.domain.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_78221786_FE25_408A_ADCE_90FE646C3AFC</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_78221786_FE25_408A_ADCE_90FE646C3AFC = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_78221786_FE25_408A_ADCE_90FE646C3AFC", editor.domain.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_C586067C_49AF_4D7C_8872_E073515E86D6</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_C586067C_49AF_4D7C_8872_E073515E86D6 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_C586067C_49AF_4D7C_8872_E073515E86D6", editor.domain.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
