/**
 * This class is generated by jOOQ
 */
package editor.domain.public_;

/**
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.ACCOUNTS
	 */
	public static final editor.domain.public_.tables.Accounts ACCOUNTS = editor.domain.public_.tables.Accounts.ACCOUNTS;

	/**
	 * The table PUBLIC.DOCUMENTS
	 */
	public static final editor.domain.public_.tables.Documents DOCUMENTS = editor.domain.public_.tables.Documents.DOCUMENTS;

	/**
	 * The table PUBLIC.DOCUMENT_SECTIONS
	 */
	public static final editor.domain.public_.tables.DocumentSections DOCUMENT_SECTIONS = editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS;

	/**
	 * The table PUBLIC.COMMENTS
	 */
	public static final editor.domain.public_.tables.Comments COMMENTS = editor.domain.public_.tables.Comments.COMMENTS;

	/**
	 * The table PUBLIC.SUGGESTIONS
	 */
	public static final editor.domain.public_.tables.Suggestions SUGGESTIONS = editor.domain.public_.tables.Suggestions.SUGGESTIONS;
}
