/**
 * This class is generated by jOOQ
 */
package editor.domain.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Catalogs extends org.jooq.impl.TableImpl<editor.domain.information_schema.tables.records.CatalogsRecord> {

	private static final long serialVersionUID = 1873974818;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.CATALOGS</code>
	 */
	public static final editor.domain.information_schema.tables.Catalogs CATALOGS = new editor.domain.information_schema.tables.Catalogs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.information_schema.tables.records.CatalogsRecord> getRecordType() {
		return editor.domain.information_schema.tables.records.CatalogsRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.CATALOGS.CATALOG_NAME</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.CatalogsRecord, java.lang.String> CATALOG_NAME = createField("CATALOG_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.CATALOGS</code> table reference
	 */
	public Catalogs() {
		this("CATALOGS", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.CATALOGS</code> table reference
	 */
	public Catalogs(java.lang.String alias) {
		this(alias, editor.domain.information_schema.tables.Catalogs.CATALOGS);
	}

	private Catalogs(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.CatalogsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Catalogs(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.CatalogsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.information_schema.tables.Catalogs as(java.lang.String alias) {
		return new editor.domain.information_schema.tables.Catalogs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.information_schema.tables.Catalogs rename(java.lang.String name) {
		return new editor.domain.information_schema.tables.Catalogs(name, null);
	}
}
