/**
 * This class is generated by jOOQ
 */
package editor.domain.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Constants extends org.jooq.impl.TableImpl<editor.domain.information_schema.tables.records.ConstantsRecord> {

	private static final long serialVersionUID = -1171465471;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.CONSTANTS</code>
	 */
	public static final editor.domain.information_schema.tables.Constants CONSTANTS = new editor.domain.information_schema.tables.Constants();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.information_schema.tables.records.ConstantsRecord> getRecordType() {
		return editor.domain.information_schema.tables.records.ConstantsRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_CATALOG</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.ConstantsRecord, java.lang.String> CONSTANT_CATALOG = createField("CONSTANT_CATALOG", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_SCHEMA</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.ConstantsRecord, java.lang.String> CONSTANT_SCHEMA = createField("CONSTANT_SCHEMA", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_NAME</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.ConstantsRecord, java.lang.String> CONSTANT_NAME = createField("CONSTANT_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.CONSTANTS.DATA_TYPE</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.ConstantsRecord, java.lang.Integer> DATA_TYPE = createField("DATA_TYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.CONSTANTS.REMARKS</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.ConstantsRecord, java.lang.String> REMARKS = createField("REMARKS", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.CONSTANTS.SQL</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.ConstantsRecord, java.lang.String> SQL = createField("SQL", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.CONSTANTS.ID</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.ConstantsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.CONSTANTS</code> table reference
	 */
	public Constants() {
		this("CONSTANTS", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.CONSTANTS</code> table reference
	 */
	public Constants(java.lang.String alias) {
		this(alias, editor.domain.information_schema.tables.Constants.CONSTANTS);
	}

	private Constants(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.ConstantsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Constants(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.ConstantsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.information_schema.tables.Constants as(java.lang.String alias) {
		return new editor.domain.information_schema.tables.Constants(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.information_schema.tables.Constants rename(java.lang.String name) {
		return new editor.domain.information_schema.tables.Constants(name, null);
	}
}
