/**
 * This class is generated by jOOQ
 */
package editor.domain.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences extends org.jooq.impl.TableImpl<editor.domain.information_schema.tables.records.SequencesRecord> {

	private static final long serialVersionUID = -1258922092;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.SEQUENCES</code>
	 */
	public static final editor.domain.information_schema.tables.Sequences SEQUENCES = new editor.domain.information_schema.tables.Sequences();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.information_schema.tables.records.SequencesRecord> getRecordType() {
		return editor.domain.information_schema.tables.records.SequencesRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.SEQUENCE_CATALOG</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.String> SEQUENCE_CATALOG = createField("SEQUENCE_CATALOG", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.SEQUENCE_SCHEMA</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.String> SEQUENCE_SCHEMA = createField("SEQUENCE_SCHEMA", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.SEQUENCE_NAME</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.String> SEQUENCE_NAME = createField("SEQUENCE_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.CURRENT_VALUE</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.Long> CURRENT_VALUE = createField("CURRENT_VALUE", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.INCREMENT</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.Long> INCREMENT = createField("INCREMENT", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.IS_GENERATED</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.Boolean> IS_GENERATED = createField("IS_GENERATED", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.REMARKS</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.String> REMARKS = createField("REMARKS", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.CACHE</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.Long> CACHE = createField("CACHE", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.MIN_VALUE</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.Long> MIN_VALUE = createField("MIN_VALUE", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.MAX_VALUE</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.Long> MAX_VALUE = createField("MAX_VALUE", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.IS_CYCLE</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.Boolean> IS_CYCLE = createField("IS_CYCLE", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SEQUENCES.ID</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SequencesRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.SEQUENCES</code> table reference
	 */
	public Sequences() {
		this("SEQUENCES", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.SEQUENCES</code> table reference
	 */
	public Sequences(java.lang.String alias) {
		this(alias, editor.domain.information_schema.tables.Sequences.SEQUENCES);
	}

	private Sequences(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.SequencesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Sequences(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.SequencesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.information_schema.tables.Sequences as(java.lang.String alias) {
		return new editor.domain.information_schema.tables.Sequences(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.information_schema.tables.Sequences rename(java.lang.String name) {
		return new editor.domain.information_schema.tables.Sequences(name, null);
	}
}
