/**
 * This class is generated by jOOQ
 */
package editor.domain.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionState extends org.jooq.impl.TableImpl<editor.domain.information_schema.tables.records.SessionStateRecord> {

	private static final long serialVersionUID = -541594341;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.SESSION_STATE</code>
	 */
	public static final editor.domain.information_schema.tables.SessionState SESSION_STATE = new editor.domain.information_schema.tables.SessionState();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.information_schema.tables.records.SessionStateRecord> getRecordType() {
		return editor.domain.information_schema.tables.records.SessionStateRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.SESSION_STATE.KEY</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SessionStateRecord, java.lang.String> KEY = createField("KEY", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SESSION_STATE.SQL</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SessionStateRecord, java.lang.String> SQL = createField("SQL", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.SESSION_STATE</code> table reference
	 */
	public SessionState() {
		this("SESSION_STATE", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.SESSION_STATE</code> table reference
	 */
	public SessionState(java.lang.String alias) {
		this(alias, editor.domain.information_schema.tables.SessionState.SESSION_STATE);
	}

	private SessionState(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.SessionStateRecord> aliased) {
		this(alias, aliased, null);
	}

	private SessionState(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.SessionStateRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.information_schema.tables.SessionState as(java.lang.String alias) {
		return new editor.domain.information_schema.tables.SessionState(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.information_schema.tables.SessionState rename(java.lang.String name) {
		return new editor.domain.information_schema.tables.SessionState(name, null);
	}
}
