/**
 * This class is generated by jOOQ
 */
package editor.domain.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings extends org.jooq.impl.TableImpl<editor.domain.information_schema.tables.records.SettingsRecord> {

	private static final long serialVersionUID = 418466408;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.SETTINGS</code>
	 */
	public static final editor.domain.information_schema.tables.Settings SETTINGS = new editor.domain.information_schema.tables.Settings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.information_schema.tables.records.SettingsRecord> getRecordType() {
		return editor.domain.information_schema.tables.records.SettingsRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.SETTINGS.NAME</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SettingsRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.SETTINGS.VALUE</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.SettingsRecord, java.lang.String> VALUE = createField("VALUE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.SETTINGS</code> table reference
	 */
	public Settings() {
		this("SETTINGS", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.SETTINGS</code> table reference
	 */
	public Settings(java.lang.String alias) {
		this(alias, editor.domain.information_schema.tables.Settings.SETTINGS);
	}

	private Settings(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.SettingsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Settings(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.SettingsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.information_schema.tables.Settings as(java.lang.String alias) {
		return new editor.domain.information_schema.tables.Settings(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.information_schema.tables.Settings rename(java.lang.String name) {
		return new editor.domain.information_schema.tables.Settings(name, null);
	}
}
