/**
 * This class is generated by jOOQ
 */
package editor.domain.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableTypes extends org.jooq.impl.TableImpl<editor.domain.information_schema.tables.records.TableTypesRecord> {

	private static final long serialVersionUID = -1599339341;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.TABLE_TYPES</code>
	 */
	public static final editor.domain.information_schema.tables.TableTypes TABLE_TYPES = new editor.domain.information_schema.tables.TableTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<editor.domain.information_schema.tables.records.TableTypesRecord> getRecordType() {
		return editor.domain.information_schema.tables.records.TableTypesRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.TABLE_TYPES.TYPE</code>.
	 */
	public final org.jooq.TableField<editor.domain.information_schema.tables.records.TableTypesRecord, java.lang.String> TYPE = createField("TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.TABLE_TYPES</code> table reference
	 */
	public TableTypes() {
		this("TABLE_TYPES", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.TABLE_TYPES</code> table reference
	 */
	public TableTypes(java.lang.String alias) {
		this(alias, editor.domain.information_schema.tables.TableTypes.TABLE_TYPES);
	}

	private TableTypes(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.TableTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private TableTypes(java.lang.String alias, org.jooq.Table<editor.domain.information_schema.tables.records.TableTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, editor.domain.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public editor.domain.information_schema.tables.TableTypes as(java.lang.String alias) {
		return new editor.domain.information_schema.tables.TableTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public editor.domain.information_schema.tables.TableTypes rename(java.lang.String name) {
		return new editor.domain.information_schema.tables.TableTypes(name, null);
	}
}
