--create table users(
--  username varchar_ignorecase(50) not null primary key,
--  password varchar_ignorecase(50) not null,
--  enabled boolean not null);
insert into users ( username, password, enabled ) values ( 'testuser@vyllage.com', 'asdf', true )

--create table authorities (
--  username varchar_ignorecase(50) not null,
--  authority varchar_ignorecase(50) not null,
--  constraint fk_authorities_users foreign key(username) references users(username));
--  create unique index ix_auth_username on authorities (username,authority);
insert into authorities ( username, authority ) values ( 'testuser@vyllage.com', 'ADMIN' )

--create table groups (
--  id bigint generated by default as identity(start with 0) primary key,
--  group_name varchar_ignorecase(50) not null);
insert into groups ( group_name ) values ( 'admins' )

--create table group_authorities (
--  group_id bigint not null,
--  authority varchar(50) not null,
--  constraint fk_group_authorities_group foreign key(group_id) references groups(id));
insert into group_authorities ( group_id, authority ) values ( 0, 'ADMIN' )

--create table group_members (
--  id bigint generated by default as identity(start with 0) primary key,
--  username varchar(50) not null,
--  group_id bigint not null,
--  constraint fk_group_members_group foreign key(group_id) references groups(id));
insert into group_members ( username, group_id ) values ( 'testuser@vyllage.com', 0 )
