create table if not exists accounts.lms_key(
  key_id bigint generated by default as identity(start with 1) primary key,
  consumer_key varchar_ignorecase(256) not null unique,
  secret varchar(256) not null,
  organization_id bigint not null,
  creator_user_id bigint not null,
  modified_by_user_id bigint not null,
  date_created timestamp not null,
  last_modified timestamp not null,
  constraint fk_lms_key_organization_organization foreign key(organization_id) references accounts.organizations(organization_id),
  constraint fk_lms_key_creator_users foreign key(creator_user_id) references accounts.users(user_id),
  constraint fk_lms_key_modified_users foreign key(modified_by_user_id) references accounts.users(user_id));