create table if not exists accounts.emails(
	email_id bigint generated by default as identity(start with 0) primary key,
	user_id bigint not null,
	email varchar_ignorecase(50) not null,
	default_email boolean not null,
	confirmed boolean not null default false,
	date_created timestamp not null,
  	last_modified timestamp not null,
	constraint fk_emails_users foreign key(user_id) references accounts.users(user_id)
);

insert into accounts.emails (user_id, email, default_email, confirmed, date_created, last_modified)  
select user_id, user_name, true, true, CURRENT_DATE(), CURRENT_DATE() from accounts.users;