create table if not exists ACCOUNTS.SOCIAL_ACCOUNT(
  social_account_id bigint generated by default as identity(start with 0) primary key,
  user_id bigint not null,
  provider_user_id varchar_ignorecase(50) not null,
  provider varchar_ignorecase(50) not null,
  enabled boolean not null,
  date_created timestamp not null,
  last_modified timestamp not null);