create table if not exists ACCOUNTS.SOCIAL_ACCOUNT(
  social_account_id bigint generated by default as identity(start with 0) primary key,
  user_id bigint not null,
  network_id varchar_ignorecase(50) not null,
  network varchar_ignorecase(50) not null,
  enabled boolean not null,
  date_created timestamp not null,
  last_modified timestamp not null);
  
  create table ACCOUNTS.UserConnection (userId varchar(255) not null,
    providerId varchar(255) not null,
    providerUserId varchar(255),
    rank int not null,
    displayName varchar(255),
    profileUrl varchar(512),
    imageUrl varchar(512),
    accessToken varchar(255) not null,
    secret varchar(255),
    refreshToken varchar(255),
    expireTime bigint,
    primary key (userId, providerId, providerUserId));

    create unique index UserConnectionRank on ACCOUNTS.UserConnection(userId, providerId, rank);