/**
 * This class is generated by jOOQ
 */
package editor.domain.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentsRecord extends org.jooq.impl.UpdatableRecordImpl<editor.domain.public_.tables.records.CommentsRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = 1687514799;

	/**
	 * Setter for <code>PUBLIC.COMMENTS.ID</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMMENTS.ID</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.COMMENTS.SECTIONID</code>.
	 */
	public void setSectionid(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMMENTS.SECTIONID</code>.
	 */
	public java.lang.Long getSectionid() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.COMMENTS.USERNAME</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMMENTS.USERNAME</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.COMMENTS.COMMENTID</code>.
	 */
	public void setCommentid(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMMENTS.COMMENTID</code>.
	 */
	public java.lang.Long getCommentid() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.COMMENTS.LASTMODIFIED</code>.
	 */
	public void setLastmodified(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMMENTS.LASTMODIFIED</code>.
	 */
	public java.sql.Timestamp getLastmodified() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return editor.domain.public_.tables.Comments.COMMENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return editor.domain.public_.tables.Comments.COMMENTS.SECTIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return editor.domain.public_.tables.Comments.COMMENTS.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return editor.domain.public_.tables.Comments.COMMENTS.COMMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return editor.domain.public_.tables.Comments.COMMENTS.LASTMODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getSectionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getCommentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getLastmodified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value2(java.lang.Long value) {
		setSectionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value3(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value4(java.lang.Long value) {
		setCommentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value5(java.sql.Timestamp value) {
		setLastmodified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.lang.Long value4, java.sql.Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CommentsRecord
	 */
	public CommentsRecord() {
		super(editor.domain.public_.tables.Comments.COMMENTS);
	}

	/**
	 * Create a detached, initialised CommentsRecord
	 */
	public CommentsRecord(java.lang.Long id, java.lang.Long sectionid, java.lang.String username, java.lang.Long commentid, java.sql.Timestamp lastmodified) {
		super(editor.domain.public_.tables.Comments.COMMENTS);

		setValue(0, id);
		setValue(1, sectionid);
		setValue(2, username);
		setValue(3, commentid);
		setValue(4, lastmodified);
	}
}
