/**
 * This class is generated by jOOQ
 */
package editor.domain.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentSectionsRecord extends org.jooq.impl.UpdatableRecordImpl<editor.domain.public_.tables.records.DocumentSectionsRecord> implements org.jooq.Record7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1458194032;

	/**
	 * Setter for <code>PUBLIC.DOCUMENT_SECTIONS.ID</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.DOCUMENT_SECTIONS.ID</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.DOCUMENT_SECTIONS.SECTIONVERSION</code>.
	 */
	public void setSectionversion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.DOCUMENT_SECTIONS.SECTIONVERSION</code>.
	 */
	public java.lang.Long getSectionversion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.DOCUMENT_SECTIONS.DOCUMENTID</code>.
	 */
	public void setDocumentid(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.DOCUMENT_SECTIONS.DOCUMENTID</code>.
	 */
	public java.lang.Long getDocumentid() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.DOCUMENT_SECTIONS.SORTORDER</code>.
	 */
	public void setSortorder(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.DOCUMENT_SECTIONS.SORTORDER</code>.
	 */
	public java.lang.String getSortorder() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.DOCUMENT_SECTIONS.JSONDOCUMENT</code>.
	 */
	public void setJsondocument(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.DOCUMENT_SECTIONS.JSONDOCUMENT</code>.
	 */
	public java.lang.String getJsondocument() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.DOCUMENT_SECTIONS.DATECREATED</code>.
	 */
	public void setDatecreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.DOCUMENT_SECTIONS.DATECREATED</code>.
	 */
	public java.sql.Timestamp getDatecreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.DOCUMENT_SECTIONS.LASTMODIFIED</code>.
	 */
	public void setLastmodified(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.DOCUMENT_SECTIONS.LASTMODIFIED</code>.
	 */
	public java.sql.Timestamp getLastmodified() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.SECTIONVERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.DOCUMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.SORTORDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.JSONDOCUMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.DATECREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS.LASTMODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getSectionversion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getDocumentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getSortorder();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getJsondocument();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getLastmodified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentSectionsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentSectionsRecord value2(java.lang.Long value) {
		setSectionversion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentSectionsRecord value3(java.lang.Long value) {
		setDocumentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentSectionsRecord value4(java.lang.String value) {
		setSortorder(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentSectionsRecord value5(java.lang.String value) {
		setJsondocument(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentSectionsRecord value6(java.sql.Timestamp value) {
		setDatecreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentSectionsRecord value7(java.sql.Timestamp value) {
		setLastmodified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentSectionsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.String value4, java.lang.String value5, java.sql.Timestamp value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DocumentSectionsRecord
	 */
	public DocumentSectionsRecord() {
		super(editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS);
	}

	/**
	 * Create a detached, initialised DocumentSectionsRecord
	 */
	public DocumentSectionsRecord(java.lang.Long id, java.lang.Long sectionversion, java.lang.Long documentid, java.lang.String sortorder, java.lang.String jsondocument, java.sql.Timestamp datecreated, java.sql.Timestamp lastmodified) {
		super(editor.domain.public_.tables.DocumentSections.DOCUMENT_SECTIONS);

		setValue(0, id);
		setValue(1, sectionversion);
		setValue(2, documentid);
		setValue(3, sortorder);
		setValue(4, jsondocument);
		setValue(5, datecreated);
		setValue(6, lastmodified);
	}
}
