/**
 * This class is generated by jOOQ
 */
package editor.domain.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuggestionsRecord extends org.jooq.impl.UpdatableRecordImpl<editor.domain.public_.tables.records.SuggestionsRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = 1850662434;

	/**
	 * Setter for <code>PUBLIC.SUGGESTIONS.ID</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.SUGGESTIONS.ID</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.SUGGESTIONS.SECTIONID</code>.
	 */
	public void setSectionid(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.SUGGESTIONS.SECTIONID</code>.
	 */
	public java.lang.Long getSectionid() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.SUGGESTIONS.SECTIONVERSION</code>.
	 */
	public void setSectionversion(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.SUGGESTIONS.SECTIONVERSION</code>.
	 */
	public java.lang.Long getSectionversion() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.SUGGESTIONS.USERNAME</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.SUGGESTIONS.USERNAME</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.SUGGESTIONS.LASTMODIFIED</code>.
	 */
	public void setLastmodified(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.SUGGESTIONS.LASTMODIFIED</code>.
	 */
	public java.sql.Timestamp getLastmodified() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return editor.domain.public_.tables.Suggestions.SUGGESTIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return editor.domain.public_.tables.Suggestions.SUGGESTIONS.SECTIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return editor.domain.public_.tables.Suggestions.SUGGESTIONS.SECTIONVERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return editor.domain.public_.tables.Suggestions.SUGGESTIONS.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return editor.domain.public_.tables.Suggestions.SUGGESTIONS.LASTMODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getSectionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getSectionversion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getLastmodified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SuggestionsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SuggestionsRecord value2(java.lang.Long value) {
		setSectionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SuggestionsRecord value3(java.lang.Long value) {
		setSectionversion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SuggestionsRecord value4(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SuggestionsRecord value5(java.sql.Timestamp value) {
		setLastmodified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SuggestionsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.String value4, java.sql.Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SuggestionsRecord
	 */
	public SuggestionsRecord() {
		super(editor.domain.public_.tables.Suggestions.SUGGESTIONS);
	}

	/**
	 * Create a detached, initialised SuggestionsRecord
	 */
	public SuggestionsRecord(java.lang.Long id, java.lang.Long sectionid, java.lang.Long sectionversion, java.lang.String username, java.sql.Timestamp lastmodified) {
		super(editor.domain.public_.tables.Suggestions.SUGGESTIONS);

		setValue(0, id);
		setValue(1, sectionid);
		setValue(2, sectionversion);
		setValue(3, username);
		setValue(4, lastmodified);
	}
}
